name: .NET Core Build and Test

on:
  push:
    branches:
  pull_request:
    branches:

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./Tests/Sistema_Bancario.csproj

    - name: List files
      run: dir ./Tests

    - name: Execute unit tests
      run: dotnet test ./Tests/Sistema_Bancario.csproj --no-restore --verbosity normal --logger "trx;LogFileName=test_results.trx"

    - name: Publish tests results
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Test Results
        path: TestResults/test_results.trx

    - name: Install PlantUML
      run: |
        choco install plantuml

    - name: Generate UML Diagram
      run: |
        # Suponha que você tenha um arquivo PlantUML, ou que você queira gerar diagramas do código.
        # Se estiver gerando a partir de código, você pode gerar o arquivo PlantUML primeiro
        # Usaremos um arquivo PlantUML de exemplo como "diagram.puml" para o diagrama.
        plantuml -tpng diagram.puml

    - name: Upload UML Diagram as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: uml-diagram
        path: diagram.png