name: .NET Core Build and Test

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./Tests/Sistema_Bancario.csproj

    - name: List files
      run: dir ./Tests

    - name: Execute unit tests
      run: dotnet test ./Tests/Sistema_Bancario.csproj --no-restore --verbosity normal --logger "trx;LogFileName=test_results.trx"

    - name: Publish test results
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Test Results
        path: TestResults/test_results.trx

    # Novo passo para configurar o PMD
    - name: Download and Setup PMD
      run: |
        curl -L -o pmd-dist-7.8.0-bin.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.8.0/pmd-dist-7.8.0-bin.zip
        unzip pmd-dist-7.8.0-bin.zip -d pmd
        rm pmd-dist-7.8.0-bin.zip

    # Novo passo para executar o CPD (detector de código duplicado)
    - name: Run CPD (Duplicate Code Detector)
      run: |
        echo "Executando o CPD (Detector de código duplicado)..."
        Start-Process -FilePath ".\pmd-bin-7.8.0\bin\pmd" -ArgumentList "cpd --minimum-tokens 40 --dir . --language cs --format text" -Wait

    # Publica o resultado da detecção de código duplicado
    - name: Upload CPD Results
      uses: actions/upload-artifact@v4.4.3
      with:
        name: CPD Results
        path: cpd-results.txt

    # Passo para exibir resultados do CPD no console
    - name: Display CPD Results
      run: cat cpd-results.txt
